#!/usr/bin/env python3
"""Build portable versions of every skill in skills/.

For each skill folder it produces:
  dist/<skill>.prompt.md   single-file prompt (SKILL.md + every bundled file inlined),
                           for chat LLMs that can't load skill folders
  build/<skill>.zip        the skill folder zipped, for tools that import skills as a zip
and one build/design-ai-infra.zip with everything.

Usage: python3 scripts/build.py
"""
import pathlib
import re
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
DIST = ROOT / "dist"
BUILD = ROOT / "build"
REPO_URL = "https://github.com/otaviosueitt33/design-ai-infra"

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)


def parse_skill(path):
    text = (path / "SKILL.md").read_text()
    m = FRONTMATTER.match(text)
    meta = {}
    for line in m.group(1).splitlines():
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    return meta, text[m.end():].lstrip()


def bundled_files(path):
    return sorted(p for p in path.rglob("*") if p.is_file() and p.name not in ("SKILL.md", "README.md") and not p.name.startswith("."))


def build_prompt(path):
    meta, body = parse_skill(path)
    title = meta["name"].replace("-", " ").title()
    files = bundled_files(path)
    parts = [
        f"<!-- Generated by scripts/build.py from skills/{path.name}. Edit the skill folder, not this file. -->",
        f"# {title} (single-file prompt)",
        "",
        f"Part of [design-ai-infra]({REPO_URL}) by Otávio Sueitt. MIT License.",
        "",
        "**How to use with any LLM:** paste this whole file as the system prompt or custom instructions "
        "(a ChatGPT custom GPT or Project, a Gemini Gem, a Claude Project, a Copilot agent, an API system prompt), "
        "or attach it to a conversation and write: *\"Follow the instructions in this file.\"*",
        "",
        "---",
        "",
        "## Instructions for the model",
        "",
        f"You are running the **{meta['name']}** skill. Follow the skill below as your instructions for this conversation. "
        "When it refers to a file such as `assets/...` or `references/...`, use the copy of that file included in "
        "\"Bundled files\" at the end of this document. Don't try to fetch it from anywhere else. "
        "If you can't create files, deliver the final document as a single Markdown code block the user can copy.",
        "",
        f"**When to use:** {meta['description']}",
        "",
        "---",
        "",
        body.rstrip(),
        "",
        "---",
        "",
        "## Bundled files",
        "",
    ]
    for f in files:
        rel = f.relative_to(path).as_posix()
        parts += [f"### File: `{rel}`", "", "````markdown", f.read_text().rstrip(), "````", ""]
    return "\n".join(parts)


def zip_dir(zf, folder, arc_root):
    for f in sorted(folder.rglob("*")):
        if f.is_file() and not f.name.startswith(".") and f.name != "README.md":
            zf.write(f, (arc_root / f.relative_to(folder)).as_posix())


def main():
    DIST.mkdir(exist_ok=True)
    BUILD.mkdir(exist_ok=True)
    skills = sorted(p for p in SKILLS.iterdir() if (p / "SKILL.md").exists())
    for skill in skills:
        (DIST / f"{skill.name}.prompt.md").write_text(build_prompt(skill))
        with zipfile.ZipFile(BUILD / f"{skill.name}.zip", "w", zipfile.ZIP_DEFLATED) as zf:
            zip_dir(zf, skill, pathlib.Path(skill.name))
        print(f"built {skill.name}")
    with zipfile.ZipFile(BUILD / "design-ai-infra.zip", "w", zipfile.ZIP_DEFLATED) as zf:
        for name in ("README.md", "LICENSE", "AGENTS.md"):
            zf.write(ROOT / name, f"design-ai-infra/{name}")
        zip_dir(zf, SKILLS, pathlib.Path("design-ai-infra/skills"))
        zip_dir(zf, DIST, pathlib.Path("design-ai-infra/dist"))
    print("built design-ai-infra.zip")


if __name__ == "__main__":
    main()
